blue:
  class_name: blue_triangle
  expected_vertices: 4
  hsv_lower:
  - 95
  - 100
  - 100
  hsv_upper:
  - 130
  - 255
  - 255
  vertex_tolerance: 3
detection:
  blur_kernel_size: 5
  dilate_iterations: 5
  epsilon_ratio: 0.03
  fill_holes: true
  max_area: 500000
  min_area: 5000
  morph_iterations: 2
  morph_kernel_size: 7
  use_convex_hull: true
yellow:
  class_name: yellow_octagon
  expected_vertices: 6
  hsv_lower:
  - 20
  - 100
  - 100
  hsv_upper:
  - 45
  - 255
  - 255
  vertex_tolerance: 4
